apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app
spec:
  destination:
    namespace: ai-planet
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Rkvishnu/ai-planet.git
    path: kubernetes
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
