apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: db-migration
        image: docker.io/rkvishnu77/demo-web:latest
        command: ["rake",  "db:migrate"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: postgres-secrets 
      restartPolicy: Never
  backoffLimit: 4                                                                                                                                                                                                        
